### ISSUE TITLE
Proper Formatting: Classes, Functions, etc.

### ISSUE THREAD

**Issue by kasp0021** [quns/OOSE2015#1]
The current code works, but is not very well organized. Before adding more, we need to put all of the code into proper classes with associated function and variables for easier reading and for "level building".

Proposed classes:
Ball. (Functions: checkCollision)
Paddle. (Variables: Top, bottom, left, right boundaries , xpos, ypos)
Blocks. (Variables: Top, bottom, left, right boundaries)

**Comment by quns** [comment]
It has been properly formatted now. :D
